[http.middlewares]
  [http.middlewares.redirect.redirectscheme]
    scheme = "https"

[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/certs/cert.crt"
        keyFile = "/certs/cert.key"
